{{- if eq .chezmoi.os "windows" }}
["AppData/Local/nvim"]
{{- else }}
[".config/nvim"]
{{- end }}
    type = "git-repo"
    url = "https://git.sr.ht/~dabe/nvim"
    refreshPeriod = "24h"

{{- if eq .chezmoi.os "linux" }}
["scripts/code-stats-zsh"]
    type = "archive"
    url = "https://gitlab.com/code-stats/code-stats-zsh/-/archive/master/code-stats-zsh-master.tar.gz"
    exact = true
    stripComponents = 1
{{- end }}
