{{ if eq .chezmoi.os "windows" }}
["AppData/Local/nvim"]
{{ else }}
[".config/nvim"]
{{ end }}
    type = "git-repo"
    url = "git@github.com:gabeklavans/nvim.git"
    refreshPeriod = "24h"

{{ if ne .chezmoi.os "windows" }}
[".zsh/code-stats-zsh"]
    type = "git-repo"
    url = "https://gitlab.com/code-stats/code-stats-zsh.git"
{{ if ne .chezmoi.hostname "gbk-work-laptop" }}
[".zsh/agkozak-zsh-prompt"]
    type = "git-repo"
    url = "git@github.com:gabeklavans/agkozak-zsh-prompt.git"
{{ end }}
{{ end }}
