{{- if eq .chezmoi.os "windows" }}
["AppData/Local/nvim"]
{{- else }}
[".config/nvim"]
{{- end }}
    type = "git-repo"
    url = "https://github.com/gabeklavans/kickstart.nvim"
    refreshPeriod = "24h"
